### ISSUE TITLE
For Brackets sprint 26, need to change isResolved()/isRejected() calls

### ISSUE THREAD

**Issue by njx** [jayproulx/git-integration#20]
In Brackets sprint 26 we're updating to jQuery 2.0, which has removed `deferred.isResolved()/isRejected()`. The correct way to check this now is to test `deferred.state() === "resolved"/"rejected"`. See http://blog.jquery.com/2012/08/09/jquery-1-8-released/ and http://api.jquery.com/deferred.state/.

You can test against Brackets master as of adobe/brackets@7588c9f.

**Comment by njx** [comment]
Note that we've also updated Bootstrap to 2.x at the same time, so you might want to check the dialog layout and make sure there aren't visual glitches. Thanks!

**Comment by jayproulx** [comment]
Fixed the jQuery issue, working on the bootstrap issue.

Openned https://github.com/pollensoft/git-integration/issues/21
