### ISSUE TITLE
minor visual glitches using Brackets Sprint 27

### ISSUE THREAD

**Issue by yanicklandry** [jayproulx/git-integration#22]
The text in Run button is not centered and there are weird transparent white rectangles on the sides.

![brackets](https://f.cloud.github.com/assets/749386/782596/70bac64c-ea3e-11e2-9feb-1bda0c4d7be5.png)

I am using Brackets Sprint 27 on Mac 10.8.4.

**Comment by jayproulx** [comment]
Thanks for the feedback Yanick!  I haven't yet been through to fix the bugs introduced when Brackets upgraded their version of Bootstrap.  I have this logged already in #21, but since you have a screenshot here, I'll close that one.

**Comment by jayproulx** [comment]
Please feel free to send a pull request if you're interested in fixing it.

**Comment by jayproulx** [comment]
Done, sorry about the wait
