### ISSUE TITLE
Upload extension to Brackets extension registry

### ISSUE THREAD

**Issue by njx** [jayproulx/git-integration#23]
Hey Jay--I was wondering if you wanted to upload your extension to the Brackets registry, so people could install it directly from the built-in Extension Manager that's in Brackets now. Here's more info on how to upload your extension to the registry: https://github.com/adobe/brackets/wiki/Extension-Registry-Help.

Also--once you've uploaded your package to the registry, if you could move it to the "Moved Extensions" section of the old Brackets Extensions wiki page (https://github.com/adobe/brackets/wiki/Brackets-Extensions) that would be great.

Thanks!

**Comment by jayproulx** [comment]
Working on this now, thanks NJ!

**Comment by jayproulx** [comment]
Fixed some bugs and moved this over, thanks for pinging me for the move request.

**Comment by njx** [comment]
Great, thanks!
